# fly.toml app configuration file generated for todolist-drf-snowy-cherry-4909 on 2025-06-27T15:43:54+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'todolist-drf-snowy-cherry-4909'
primary_region = 'hkg'
console_command = '/code/manage.py shell'

[build]

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
